version: '2'
services:
    fullstacktemp-app:
        image: thamizhelango/fullstacktemp:1.0
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fullstacktemp-mysql:3306/fullstacktemp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fullstacktemp-mysql:
        extends:
            file: mysql.yml
            service: fullstacktemp-mysql
